version: '2'
services:
    mysql:
        image: "mysql:5.7" 
        network_mode: "host"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "root"
            MYSQL_PASS: "root"
        ports: 
            - "3306:3306"
        restart: always
        volumes:
            - "./db:/var/lib/mysql"
            - "./conf/my.cnf:/etc/my.cnf"

